# Generated by Django 5.1 on 2024-09-01 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.categoria')),
            ],
            options={
                'ordering': ['-fecha_entrada'],
                'indexes': [models.Index(fields=['nombre_producto'], name='admin_panel_nombre__79eac0_idx'), models.Index(fields=['fecha_entrada'], name='admin_panel_fecha_e_072569_idx')],
            },
        ),
    ]
